### ISSUE TITLE
Transaction operation issue

### ISSUE THREAD

**Issue by ghost** [bigchaindb/java-bigchaindb-driver#2]
In BigchainDbTransactionBuilder.build() method 
instead of using:
if (this.transaction.getOperation() == null)     // line 167
need to be 
(this.operation  == null)
Without this change this.transaction.getOperation()  always null.

**Comment by innopreneur** [comment]
Thanks @NikitaLos. I will check it out and if there is a problem and this fixes it, I will update it.
Maybe in future, you can also create PRs, as it can be merged easily and you will have a badge of contributor :)

**Comment by ghost** [comment]
Ok, got it)
