### ISSUE TITLE
Failure to send transaction to testnet

### ISSUE THREAD

**Issue by adonnini** [bigchaindb/java-bigchaindb-driver#36]
Hi,

All of a sudden (9/27 after 6 PM Berlin time) sending transactions to the testnet fails with the following failure

09-27 13:00:02.200: W/System.err(5687): javax.net.ssl.SSLHandshakeException: Connection closed by peer
09-27 13:00:02.200: W/System.err(5687): at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
09-27 13:00:02.200: W/System.err(5687): at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-27 13:00:02.200: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-27 13:00:02.201: W/System.err(5687): at com.bigchaindb.builders.BigchainDbConfigBuilder$Builder$2.intercept(BigchainDbConfigBuilder.java:199)
09-27 13:00:02.201: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-27 13:00:02.201: W/System.err(5687): at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-27 13:00:02.201: W/System.err(5687): at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
09-27 13:00:02.201: W/System.err(5687): at okhttp3.RealCall.execute(RealCall.java:77)
09-27 13:00:02.201: W/System.err(5687): at com.bigchaindb.util.NetworkUtils.sendGetRequest(NetworkUtils.java:80)
09-27 13:00:02.201: W/System.err(5687): at com.bigchaindb.builders.BigchainDbConfigBuilder$Builder.setup(BigchainDbConfigBuilder.java:152)

**Comment by ttmc** [comment]
Thanks for filing this bug report, @adonnini 

Could you give some more details:

- What operating system (and version) are you using?
- What version of the Java driver?
- Are you able to reproduce this error, i.e. starting from a fresh state?
- Are all posted transactions failing to get though after some point? If so, do you know what the trigger was? Is it random? Is it some specific transaction?

As I write this, the BigchainDB Testnet is up and running, and when I post a new transaction to it from the page https://www.bigchaindb.com/developers/getstarted/ it works. (That page uses the JavaScript driver though.) Therefore the problem isn't with the testnet.

Did you try Googling the error message, such as `javax.net.ssl.SSLHandshakeException: Connection closed by peer`

**Comment by adonnini** [comment]
I inserted answers to the best of my ability in line below.

Thanks,

Alex

Troy McConaghy wrote:
>
> Thanks for filing this bug report, @adonnini <https://github.com/adonnini>
>
> Could you give some more details:
>
>   * What operating system (and version) are you using?
>
Android 8.0
>
>   * What version of the Java driver?
>
1.1
>
>   * Are you able to reproduce this error, i.e. starting from a fresh
>     state?
>
Yes
>
>   * Are all posted transactions failing to get though after some
>     point? If so, do you know what the trigger was? Is it random? Is
>     it some specific transaction?
>
All transactions cannot be posted. The same code worked until earlier today

                     Transaction transaction = new Transaction();
                     try {
                         transaction = BigchainDbTransactionBuilder
                                 .init()
                                 .addAssets(assetDataMap, TreeMap.class)
                                 .addAssetDataClass(TreeMap.class, null)
                                 .operation(Operations.CREATE)
                                 .buildAndSign((EdDSAPublicKey) 
keyPair.getPublic(), (EdDSAPrivateKey) keyPair.getPrivate())
.sendTransaction(handleServerResponse());

**Comment by adonnini** [comment]
Hi,

Problem solved??

I am at a different location. The problem does not occur any longer.

Thanks,

Alex Donnini

Troy McConaghy wrote:

**Comment by ttmc** [comment]
I'm not an expert on Android or Java, but our local expert was going to take a look at this today.

Looking at the error messages, it seems that something happened on your Android device causing SSL/TLS to stop working properly.

**Comment by adonnini** [comment]
I think you may be right. As of now, the problem is not occurring any longer.

Thanks,

Alex

Troy McConaghy wrote:

**Comment by innopreneur** [comment]
Thanks @adonnini for confirming. I also didn't think its anything related to the driver. So, I am gonna close this issue, if its alright.
