### ISSUE TITLE
example of asset data update

### ISSUE THREAD

**Issue by dolphinsd** [bigchaindb/java-bigchaindb-driver#43]
We are trying to use the driver to do an asset data update. Just like in javascript but failed to see a proper syntax. How would one update the asset with new values?
Or the only way to add addition attributes to the asset is via metadata update?

**Comment by ttmc** [comment]
One does not delete or change existing data (stored transactions) in a blockchain. The only option is to push new data (new transactions).

The typical way to model a changing asset is to have a chain of TRANSFER transactions, even if they don't change the owner. The metadata in the TRANSFER transaction can say what changed.

**Comment by dolphinsd** [comment]
@ttmc thanks. that is what we thought. thanks for confirmation.

**Comment by vellotis** [comment]
Just for increasing the visibility: https://gist.github.com/innoprenuer/d4c6798fe5c0581c05a7e676e175e515
